#pragma config(StandardModel, "EV3_REMBOT")
//#include "checkCost.c"

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//RGB Type
typedef struct{
	long red;
	long green;
	long blue;
	int cost;
}RGB;

void printLayar(long red, long green, long blue){
		writeDebugStreamLine("R : %ld",red);
		writeDebugStreamLine("G : %ld",green);
		writeDebugStreamLine("B : %ld",blue);
		getColorRGB(colorSensor,red,green,blue);
		displayTextLine(2,"R : %ld",red);
		displayTextLine(3,"G : %ld",green);
		displayTextLine(4,"B : %ld",blue);
}

void printJarak(int jarakSementara){
		writeDebugStreamLine("Jarak : %d",jarakSementara);
		displayTextLine(5,"Jarak : %d",jarakSementara);
}

bool isIntersection(long red, long green, long blue){
	//hijau tanda persimpangan biasanya terdeteksi dengan nilai R mendekati 0, G mendekati 100 dan B mendekati 0
	if((red<= 25) && (green>=30) && (blue<=20)){
	  return true;
  } else {
  	return false;
  }
}

bool isStop(long red, long green, long blue){
	//hijau tanda persimpangan biasanya terdeteksi dengan nilai R mendekati 0, G mendekati 100 dan B mendekati 0
	if((red>=90) && (green>=87) && (green>=37) && (blue<=35)){
	  return true;
  } else {
  	return false;
  }
}

int checkCost(long r, long g, long b){
	int x = -1;
	//HEURISTIC TABLE
	RGB HTable[25];
	HTable[0].red=42;HTable[0].green=59;HTable[0].blue=27.5;//
	HTable[1].red=60.5;HTable[1].green=40;HTable[1].blue=25;//
	HTable[4].red=45.5;HTable[4].green=41;HTable[4].blue=12.5;//
	HTable[5].red=42.5;HTable[5].green=50;HTable[5].blue=48;//
	HTable[6].red=67.5;HTable[6].green=81;HTable[6].blue=20;
	HTable[7].red=100;HTable[7].green=50;HTable[7].blue=0;
	HTable[8].red=33.5;HTable[8].green=50.5;HTable[8].blue=32.5;
	HTable[9].red=47.5;HTable[9].green=23;HTable[9].blue=19;
	HTable[10].red=100;HTable[10].green=93;HTable[10].blue=34.5;
	HTable[11].red=54;HTable[11].green=64;HTable[11].blue=30;
	HTable[13].red=100;HTable[13].green=0;HTable[13].blue=50;
	HTable[14].red=54;HTable[14].green=48.5;HTable[14].blue=29;
	HTable[16].red=68.5;HTable[16].green=87.5;HTable[16].blue=31;
	HTable[17].red=100;HTable[17].green=35.5;HTable[17].blue=45;
	HTable[18].red=55;HTable[18].green=58;HTable[18].blue=50;
	HTable[20].red=50;HTable[20].green=0;HTable[20].blue=100;
	HTable[23].red=0;HTable[23].green=100;HTable[23].blue=100;
	HTable[24].red=82.5;HTable[24].green=54;HTable[24].blue=36.5;
	for (int i=0;i<=24;i++){
			if((i!=2) && (i!=3) && (i!=12) && (i!=15) && (i!=19) && (i!=21) && (i!=22)){
				int range;
				if(isIntersection(r,g,b)){
				  return 100;
			  }
			  if(isStop(r,g,b)){
				  return 101;
			  }
				if(i==14){//pengecualian untuk abu2
				 	range = 5;
				} else {
					range = 25;
				}
				if((r <= HTable[i].red + range) && (r >= HTable[i].red - range) && (g >= HTable[i].green - range) && (g <= HTable[i].green + range) && (b >= HTable[i].blue - range) && (b <= HTable[i].blue + range)){
					x = i;
					break;
				}
			}
	}
	return x;

}

task main()
{
	long red,green,blue;
	float jarakSementara = 0;
	// sensor sees light:
	resetTimer(timer1);
	int costWarna;
  while(true)
  {
		printLayar(red,green,blue);
		getColorRGB(colorSensor,red,green,blue);
		if(red < 20 && green < 20 && blue < 20)
    {
      // counter-steer left:
      motor[leftMotor]  = 25;
      motor[rightMotor] = 15;
    }
    // sensor sees dark:
    else if (red > 70 && green > 70 && blue > 70)
    {
    	//counter right
    	motor[leftMotor]  = 5;
      motor[rightMotor] = 25;
    }
    //sensor sees light
    else
    {
    	//go straight
      motor[leftMotor]  = 20;
      motor[rightMotor] = 20;
      sleep(200);
    	costWarna = checkCost(red,green,blue);
    	if (costWarna == 100) //intersection green
    	{
    		motor[leftMotor]  = 0;
      	motor[rightMotor] = 0;
      	sleep(1000);
      	displayTextLine(7,"detected intersection");
      } else if (costWarna == 101) //intersection green
    	{
    		turnLeft();
    		turnLeft();
      	sleep(1000);
      	displayTextLine(7,"detected stop turn around");
      }
      displayTextLine(6,"costWarna = %d",costWarna);


    }

    jarakSementara = getTimer(timer1, seconds);

    printJarak(jarakSementara);
  }
}
